AddonId: GridViewCards_9af15fb8-f51c-45df-93fc-235c50bfcd39
Packages:
  - Version: 0.1
    RequiredApiVersion: 2.1.0
    ReleaseDate: 2022-01-12
    PackageUrl: https://github.com/JG00SE/GridViewCards/releases/download/0.1/GridViewCards_9af15fb8-f51c-45df-93fc-235c50bfcd39_0_1.pthm
    Changelog:
      - First upload for testing

